---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hipstert/public_html
    - /usr/bin/rsync -rlt --chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r --exclude='.git' --exclude='.gitignore' --exclude='.cpanel.yml' --exclude='.env' --exclude='.user.ini' ./ $DEPLOYPATH/
